// global
export const TOGGLE_COLLAPESD = "TOGGLE_COLLAPESD";
export const CHANGE_TAB = "CHANGE_TAB";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_SUCCESS = "FETCH_SUCCESS";

// user
export const GET_USER = "GET_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REG_SUCCESS = "REG_SUCCESS";
export const LOGOUT = "LOGOUT";

// file
export const CHANGE_SELECTED_FILE = "CHANGE_SELECTED_FILE";
export const UPDATE_FILES = "UPDATE_FILES";
export const UPDATE_SELECTED_ROW_KEYS = "UPDATE_SELECTED_ROW_KEYS";
export const CHANGE_DELETE_LOADING = "CHANGE_DELETE_LOADING";
export const CHANGE_DOWNLOAD_LOADING = "CHANGE_DOWNLOAD_LOADING";
