// global
export const TOGGLE_COLLAPESD = "TOGGLE_COLLAPESD";
export const CHANGE_TAB = "CHANGE_TAB";

// user
export const GET_USER = "GET_USER";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REG_SUCCESS = "REG_SUCCESS";
export const LOGOUT = "LOGOUT";

// file
export const CHANGE_SELECTED_FILE = "CHANGE_SELECTED_FILE";
export const FETCH_FILE_REQUEST = "FETCH_FILE_REQUEST";
export const FETCH_FILE_FAILURE = "FETCH_FILE_FAILURE";
export const FETCH_FILE_SUCCESS = "FETCH_FILE_SUCCESS";
export const UPDATE_FILES = "UPDATE_FILES";
export const UPDATE_SELECTED_ROW_KEYS = "UPDATE_SELECTED_ROW_KEYS";
